version: '3.8'
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: company
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 3

    mail-app:
        build:
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        depends_on:
            mysql:
                condition: service_healthy